version: '3.7'
services:
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    command: ['npm', 'start']
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ['flask', 'run', '--host=0.0.0.0']
    ports:
      - '5000:5000'
    networks:
      - frontend
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
